### ISSUE TITLE
Google Social Auth + WP plugin - How restrict users based on groups?

### ISSUE THREAD

**Issue by zorbon90** [ForgeRock/openam-authentication#5]
Hello,
how can I restrict users which can login (based on group) to Wordpress site with this plugin?

I try apply policies with patterns for site, but user which isn't in this group can still log in.

Thanks for help or idea.

**Comment by forgerock1** [comment]
This plugin is only doing SSO, it is not applying authorisation. If you need to authorize. It might be better to use the Apache Policy Agent for OpenAM
