### ISSUE TITLE
Login via OpenAM displays WordPress login screen

### ISSUE THREAD

**Issue by johnarends** [ForgeRock/openam-authentication#6]
If a user goes directly to a URL like http://server.com/wordpressblog/wp-admin/, we get an OpenAM login prompt, and after successfully logging in, the user then gets a standard WordPress login screen.

If the user hits the "Back to <blog name>" link, and hits the "Log In" link on that blog, the user is able to successfully view the Dashboard.

Subsequent visits directly to  http://server.com/wordpressblog/wp-admin/ work just fine after this point.

Simply a first visit to  http://server.com/wordpressblog/wp-admin/ when a user has not yet authenticated to OpenAm causes these problems.

Further testing shows that the plugin only realizes that we are logged in if we trigger this URL:

https://openamserver.company.com/amserver/UI/Login?realm=/&goto=http%3A%2F%2Fserver.com%2Fblogname%2Fwp-login.php

Is there a way we could put that link on the WP login screen to allow people to push forward in the event they bookmark http://server.com/wordpressblog/wp-admin/ directly?

Edit:

This problem was largely solved by "Page to go after OpenAM Successful login" in version 1.4. I just realized that version had been released.

**Comment by forgerock1** [comment]
Hi Johnarends.
Thanks for the feedback.
Is it now working fine with you now in  version 1.4?
